### PR TITLE
Consistently use ns for namespace in docs/examples

### PR DESCRIPTION
**Pull request by MarcoGorelli**
`namespace = dataframe.__dataframe_namespace__()` is quite verbose, how about just using a 2-letter acronym in the examples? most people alias namespace to 2-letter acronyms anyway

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks Marco. This makes sense to me. I was never quite a fan of the `namespace` name. `ns` seems better - or something like `pdx` would work too (we use `xp` on the array side).

**Comment by MarcoGorelli** [comment]
thanks - yeah thought of `pdx` too but it struck me as too `pandas-centric`

**Comment by rgommers** [comment]
Makes sense. Let's see if anyone else has a strong opinion - if not, then let's merge within a couple of days.

**Comment by kkraus14** [comment]
For what it's worth, I interpret `pdx` as `Python DataFrame X` and unrelated to pandas, so I'd be +1 to that. `ns` makes me think nanoseconds 😆

**Review by kkraus14 — APPROVED** [review]

**Pull request merged**
