### PR TITLE
add an `__invert__` method to `DataFrame`

### PR DESCRIPTION
**Pull request by MarcoGorelli**
as discussed on the call

### CODE REVIEW

**Comment by jbrockmendel** [comment]
does `__invert__` raise on non-boolean dtypes?  xref https://github.com/pandas-dev/pandas/issues/51567

**Comment by MarcoGorelli** [comment]
yeah it should do. quite a few of these should raise in such cases (e.g. any, all)

**Comment by rgommers** [comment]
Can you add that it must raise an exception on all dtypes except bool Marco, and resolve the merge conflict? Then this looks good to go.

**Review by rgommers — APPROVED** [review]
LGTM now

**Pull request merged**
