### PR TITLE
rename isnull and isnan methods

### PR DESCRIPTION
**Pull request by MarcoGorelli**
as discussed on the last call

### CODE REVIEW

**Comment by rgommers** [comment]
I don't remember what the rationale for this was, can you add one @MarcoGorelli? These methods are using the no-underscore flavor pretty much universally I think, and also in the array API for `isnan`.

**Comment by MarcoGorelli** [comment]
just snake-case - you'd read it as "is null", and replacing the space with an underscore, would get "is_null"

**Comment by rgommers** [comment]
Hmm - I'd think that that's probably not a good reason for `is` and `has`, they're kinda special in Python (`isinstance`, `issubclass`, `hasattr`, etc.) - that plus `isnan`/`isnull` being the current names everywhere means we should probably leave this as is.

**Comment by jorisvandenbossche** [comment]
> everywhere

Just to be pedantic, but not "everywhere": for example pyarrow and polars both use "is_null" etc (but yeah, those are certainly the outliers and probably less relevant for the exercise here)

**Pull request closed without merging**
