### PR TITLE
rename get_column_by_name to col

### LINKED ISSUE #287: Feature request: `get_column_by_name` impairs readability
Hey dataframe-api team!

First off, thank you for this effort. I'm a developer of [skrub](https://github.com/skrub-data/skrub), a data-wrangling package. We aim to support many dataframes, starting with Pandas and Polars, and currently have duplicate logic.

We think the dataframe-API is the way for us (see [this discussion](https://github.com/skrub-data/skrub/discussions/719)) and hope to make the switch soon.

I followed the discussion of https://github.com/data-apis/dataframe-api/pull/249 and I'm pretty upset about having to use `df.get_column_by_name("a")` instead of a simpler `df["a"]` or `col("a")`. This will obfuscate our code and impair readability, and therefore we may consider keeping our duplicate logic.

To keep an acceptable UX, could we consider having at least a shorter alias to `get_column_by_name`?

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #287

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Review by shwina — APPROVED** [review]
I'm +1 to this, but would prefer if we brought this up in the next meeting before merging. Thanks!

**Comment by MarcoGorelli** [comment]
sure, will wait, thanks

**Review by rgommers — APPROVED** [review]
For context, I think we inherited the `get_column_by_name` method naming from the interchange protocol. For that protocol, usage is kind of a "one shot" thing, where you may use a few methods when doing a conversion, but it's not like you write a whole library using that API. There is no real reason why we have to keep names that are in the interchange protocol, and `get_column_by_name` is particularly cumbersome, so +1 to renaming. Any reasonable and ergonomic name works here (`.col`, `.get_col`, etc.), so +1 from me.

The one thing to keep in mind for future renames is probably that we should avoid having method names that are also part of the protocol if the semantics are different. But that doesn't seem too likely.

**Comment by MarcoGorelli** [comment]
approved in today's call too - thanks all, let's get this in and make things happen

**Pull request merged**
