### PR TITLE
Add some cumulative Column operations

### PR DESCRIPTION
**Pull request by MarcoGorelli**
I noticed plotly uses some cumulative functions (`Series.cumsum`) - OK to start adding some simple and common cumulative operations to `Column`?

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
If we add them, we might want to use the full name (cumulative_...), xref https://github.com/data-apis/array-api/issues/597#issuecomment-1431152772

**Comment by kgryte** [comment]
These APIs are likely to be added to the 2023 revision of the array API standard. May be preferable to either wait until the naming convention is sorted there, or help participate in that discussion. Apart from `cumulative_sum`, another alternative is `cusum`.

**Comment by MarcoGorelli** [comment]
have updated, thanks

let's go with `cumulative_`, and we can always update later again if necessary?

**Comment by rgommers** [comment]
> let's go with `cumulative_`, and we can always update later again if necessary?

That sounds fine to me - keeps the ball rolling.

**Review by rgommers — APPROVED** [review]
This seems fine to me, thanks Marco. Assuming folks want the min/max too; they seem commonly implemented in dataframe libraries at least. 

And checking: typing is going to need `Column[Any]` perhaps, given the other typing PR?

**Comment by MarcoGorelli** [comment]
for sum and prod, yes

for `cumulative_min` and `cumulative_max`, I think we could be more precise: `Column[DType]` (it should be preserved for these two operations, right?)

**Pull request merged**
